//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWeibo.WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iWeibo.WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号 的本地化字符串。
        /// </summary>
        public static string AccountText {
            get {
                return ResourceManager.GetString("AccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加位置 的本地化字符串。
        /// </summary>
        public static string AddLocationText {
            get {
                return ResourceManager.GetString("AddLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加图片 的本地化字符串。
        /// </summary>
        public static string AddPhotoText {
            get {
                return ResourceManager.GetString("AddPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同时发送到新浪微博 的本地化字符串。
        /// </summary>
        public static string AlsoSendSinaText {
            get {
                return ResourceManager.GetString("AlsoSendSinaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同时发送到腾讯微博 的本地化字符串。
        /// </summary>
        public static string AlsoSendTencentText {
            get {
                return ResourceManager.GetString("AlsoSendTencentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单项 的本地化字符串。
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱微博 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提及 的本地化字符串。
        /// </summary>
        public static string AtText {
            get {
                return ResourceManager.GetString("AtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写微博 的本地化字符串。
        /// </summary>
        public static string CreateNewText {
            get {
                return ResourceManager.GetString("CreateNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再按一次后退键退出 的本地化字符串。
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏 的本地化字符串。
        /// </summary>
        public static string FavoritesText {
            get {
                return ResourceManager.GetString("FavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转发 的本地化字符串。
        /// </summary>
        public static string ForwardText {
            get {
                return ResourceManager.GetString("ForwardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePageText {
            get {
                return ResourceManager.GetString("HomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据请求中... 的本地化字符串。
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string MainPageText {
            get {
                return ResourceManager.GetString("MainPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-CN 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在发送... 的本地化字符串。
        /// </summary>
        public static string SendingText {
            get {
                return ResourceManager.GetString("SendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定新浪微博 的本地化字符串。
        /// </summary>
        public static string SinaBindingText {
            get {
                return ResourceManager.GetString("SinaBindingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新浪微博 的本地化字符串。
        /// </summary>
        public static string SinaTitle {
            get {
                return ResourceManager.GetString("SinaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定腾讯微博 的本地化字符串。
        /// </summary>
        public static string TencentBindingText {
            get {
                return ResourceManager.GetString("TencentBindingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腾讯微博 的本地化字符串。
        /// </summary>
        public static string TencentTitle {
            get {
                return ResourceManager.GetString("TencentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 话题 的本地化字符串。
        /// </summary>
        public static string TopicText {
            get {
                return ResourceManager.GetString("TopicText", resourceCulture);
            }
        }
    }
}
